### ISSUE TITLE
User thumbnails are very low quality

### ISSUE THREAD

**Issue by jaygarcia** [moduslabs/modir#116]
Can we please choose a higher quality photo from the Slack API to render thumbnails? They are very low quality and are scaled up.

Thumb:
![image](https://user-images.githubusercontent.com/180031/120339876-7e66a700-c2c3-11eb-91c8-5328f90f747b.png)

Thumb in the app (notice it's blurry).
![image](https://user-images.githubusercontent.com/180031/120339779-6727b980-c2c3-11eb-87f9-c0d2e0d93226.png)

**Comment by rodriguezmanu** [comment]
merged https://github.com/moduslabs/modir/pull/118
