### ISSUE TITLE
Slack image failures (stale data?) for Jonathan Caballero & Jay Garcia

### ISSUE THREAD

**Issue by jaygarcia** [moduslabs/modir#39]
Seems like there is a two problems with the slack data that may be related:

- Image data is old for the slack user 
- Old images are no longer hosted by 

#  Jonathan Caballero
https://dir.modus.app/details/U0AV0F4EM

His `real` slack image:  https://ca.slack-edge.com/T025W8CSY-U0AV0F4EM-5f103b9cd707-72

![](https://ca.slack-edge.com/T025W8CSY-U0AV0F4EM-5f103b9cd707-72)

Search shows the old image:
![image](https://user-images.githubusercontent.com/180031/56753113-da12ed80-6757-11e9-8660-e4f63e5a7081.png)

Exception in browser:
```
585362525239_54c1816ccf29d0490c15_72.jpg:1 Failed to load resource: the server responded with a status of 403 ()
```

URL for JPG:
`https://avatars.slack-edge.com/2019-03-21/585362525239_54c1816ccf29d0490c15_72.jpg`

![image](https://user-images.githubusercontent.com/180031/56752403-2b21e200-6756-11e9-96ab-8fde58ae113c.png)

# Jay Garcia

Search for `Jay Garcia`, a broken image shows up in the results. Click on the record, the image appears. Search again, the image appears.  Still the wrong image.

Current image:
![](https://ca.slack-edge.com/T025W8CSY-U0B6XKFBL-2844f5cfa408-72)

![Apr-25-2019 12-43-25](https://user-images.githubusercontent.com/180031/56753256-34ac4980-6758-11e9-9a56-46e675cc1553.gif)

**Comment by jaygarcia** [comment]
Happens for Diego Gil too:

![image](https://user-images.githubusercontent.com/180031/56753752-45a98a80-6759-11e9-8044-f76fcd9b8e1e.png)

![image](https://user-images.githubusercontent.com/180031/56753759-49d5a800-6759-11e9-9180-c61146ef6ad3.png)

**Comment by mitchellsimoens** [comment]
Looks like the code for the `modites` script has the stale data. Looking at what slack currently sends for jay and diego, they have different images for the `image_192` field (it's the field that the details view uses for the image). I hit the individual `modite` route with jay's ID and it returned the same image that slack returned. Now if I go to jay's detail view, I can now see his current image. So looks like the `modites` route does not update the cached info.

So, looking at the `modites` script, in the `appendModiteProfiles` function, it doesn't have any code that refetches information from slack, it just uses the last JSON blob that is stored and that's ok. I'd hate for the `modites` script to pull all details for every modite always.

So, the details view could hit that individual `modite` route that should get the latest info but that would only solve that one view, the list will still show old data until that individual modite is hit. This is not optimal, we'll still be using stale data. We may need a nightly updater but then we have the google token to deal with.

Thoughts?

**Comment by jaygarcia** [comment]
this looks like it was resolve.  :D
