### ISSUE TITLE
Automation feeding Modir is failing due to 2FA

### ISSUE THREAD

**Issue by jaygarcia** [moduslabs/modir#62]
When google auth was enabled for Harvest, it broke API access for the current scripts.  Definitely need to get this resolved as the data is currently stale.

**Comment by obscurerichard** [comment]
Harvest and HeyTaco both seem to not have current data represented

**Comment by jaygarcia** [comment]
Authentication to this API has been resolved, however there is now a problem with the Key-Value store not working appropriately. :(

**Comment by jaygarcia** [comment]
This is done
